name: Auto crawl tasks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - shell: bash
      run: |
        echo -e "DS_KEY=$DS_KEY       \n"  > .env
        echo -e "SUPA_URL=$SUPA_URL   \n" >> .env
        echo -e "SUPA_ANON=$SUPA_ANON"    >> .env


    - run: |
        export DS_KEY="${{ secrets.DS_KEY }}"
        export SUPA_URL="${{ secrets.SUPA_URL }}"
        export SUPA_ANON="${{ secrets.SUPA_ANON }}"
        export

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run main.py
      run: python main.py
